### ISSUE TITLE
Linux executable requires addional permissions first

### ISSUE THREAD

**Issue by chanjuping** [TechsLearner2/J.O.R.T.N#2]
Just a passing comment. Thanks for making the game available for Linux.

You can add to the documentation that to run the game on Linux, the executable file J.O.R.T.N.x86_64 should be given executable permission using the command:

`chmod +x J.O.R.T.N.x86_64`

**Comment by TechsLearner2** [comment]
Thank you ... We're working on it 

Stay Tuned With The Zombie Squad
